# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

matrix:
  include:
    - r: release
    - r: devel
