// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LtoEAP_cpp
List LtoEAP_cpp(const arma::mat& L, const arma::mat& theta_grid, const arma::colvec& prior_density);
RcppExport SEXP _PROsetta_LtoEAP_cpp(SEXP LSEXP, SEXP theta_gridSEXP, SEXP prior_densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_grid(theta_gridSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type prior_density(prior_densitySEXP);
    rcpp_result_gen = Rcpp::wrap(LtoEAP_cpp(L, theta_grid, prior_density));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PROsetta_LtoEAP_cpp", (DL_FUNC) &_PROsetta_LtoEAP_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_PROsetta(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
