# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
LtoEAP_cpp <- function(L, theta_grid, prior_density) {
    .Call('_PROsetta_LtoEAP_cpp', PACKAGE = 'PROsetta', L, theta_grid, prior_density)
}

